pipeline {
	agent any
	stages{

		stage('clean_up'){
			
			steps{
			   catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE'){
			   sh ' docker image prune -a --force --filter "until 20h" '
			   sh ' docker container rm -f c1 '
			   }
			}
		}
		stage('image_build'){
			steps{
			   sh '''
			     
				docker image build -t v1 /home/ec2-user/Ishmail/7AM_Devops/docker/apache/ 
			   '''
			}
		}

		stage('image_tag'){
			steps{
			   sh '''
				docker image tag v1:latest ishmailc/v1:latest
			   '''
			}
		}

		stage('container_creation'){
			steps{
			   sh '''
				docker run -d --name c1 ishmailc/v1:latest bash
			   '''
			}
		}
}
}
