s = "ishmaiLC123"
print("\n\n---------String & String Function----------\n\n")
print("-----------------------------------------")
print("Original string is : " + s)
print("String type is     : ", type(s))
print("-----------------------------------------\n\n")
print("Length of string                 : ", len(s))
u = print("To UPPERCASE                     : " + s.upper())
l = print("To lowercase                     : " + s.lower())
print("First letter Capital             : " + s.capitalize())
print("As a Title                       : " + s.title())
print("string count                     : ", s.count("i"))
print("Ends with \"iL\"                 : ", s.endswith("iL"))
print("Ends with \"123\"                : ", s.endswith("3"))
print("Find chat \"i\" position         : ", s.find("i"))
print("Find chat \"i\" position         : ", s.find("i", 1))
print("Find \'i\' and replace \'6\'     : ", s.replace("i", '6'))
print("Is UPPERCASE                     : ", s.isupper())
print("Is lower                         : ", s.islower())
print("Is alphanumeric                  : ", s.isalnum())
print("Is alpha                         : ", s.isalpha())
print("Is decimal                       : ", s.isdecimal())
print("Is digit                         : ", s.isdigit())
print("Is numeric                       : ", s.isnumeric())
