---
  - name: Ec2 Instance creation
  amazon.aws.ec2:
  hosts: localhost
  tasks:
   state: Create
   region: us-east-1
  image: ami-065efef2c739d613b
  instance_type: t2.micro
   wait: yes
  count: 1
  vpc_subnet_id: vpc-022526464d588bb3d
  volumes:
   - devise_name: /dev/xvda
   snapshot: snap-0c87771c8e09de699
   volume_type: gp2
   volume_size: 8
  instance_tags:
    Name: Ansible
  security_group: Linuxall
   key_name: Key1
...
